# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew formula generator.
# Description: macOS Network Usage Monitor
class Netmon < Formula
  desc "macOS Network Usage Monitor - Track network usage by interface and application"
  homepage "https://github.com/abcdOfficialzw/netmon"
  url "https://github.com/abcdOfficialzw/netmon/archive/refs/heads/main.tar.gz"
  version "0.1.0"
  sha256 "091a34611ef54350d11c557715af8c096079a259eb3ce866755edbe32e8bab52"
  license "MIT"
  head "https://github.com/abcdOfficialzw/netmon.git", branch: "main"

  depends_on "go" => :build

  def install
    # Set up Go environment
    ENV["GOPATH"] = buildpath
    ENV["GO111MODULE"] = "on"

    # Create directory structure
    (buildpath/"src/netmon").install buildpath.children - [buildpath/".brew_home"]

    cd "src/netmon" do
      # Build netmon-service
      system "go", "build", "-o", bin/"netmon-service", "./cmd/netmon-service"

      # Build netmon CLI
      system "go", "build", "-o", bin/"netmon", "./cmd/netmon"
    end
  end

  test do
    # Test that binaries exist and are executable
    assert_match "Usage:", shell_output("#{bin}/netmon 2>&1", 1)
    assert_match "Usage of", shell_output("#{bin}/netmon-service --help 2>&1")
  end

  def post_install
    # Print helpful message after installation
    ohai "netmon installed successfully!"
    ohai ""
    ohai "Next steps:"
    ohai "  1. Run: netmon setup"
    ohai "  2. This will configure the background service"
    ohai "  3. Then use: netmon (to view stats)"
    ohai ""
    ohai "For more info, visit: #{homepage}"
  end
end

